In [142]:
# !pip install -r requirements.txt

In [143]:
## importing libraries
import numpy as np
import pandas as pd
import nltk
import matplotlib.pyplot as plt
import seaborn as sns

import re
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [144]:
df = pd.read_csv("emails.csv")
df.head()
## Spam---> 1 Ham-->0

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [145]:
## shape of the dataset
df.shape

(5728, 2)

In [146]:
## Individual mails
df["text"][0]

"Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  marketing break - through shouldn ' t make gaps in your budget . 100 % satisfaction  guaranteed : we provide unlimited amount of changes with no extra fees for you to  be surethat you will love the result of this collaboration . have a look at our  portfolio _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ not interested . . . _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"

## Text Preprocessing: - 
1. Handle duplicate ---> Done
2. Handle Mising Values ----> No missing values were present.
3. lowering all the text ---> Done
4. Stopwords ---> Done
5. Lemmatization ---> Done
6. Converting text to vectors
7. ML algorithm

In [147]:
## duplicates
df.duplicated().sum()

np.int64(33)

In [148]:
## removing of duplicates
df.drop_duplicates(inplace=True)

In [149]:
df.duplicated().sum()

np.int64(0)

In [150]:
## missing values
df.isnull().sum()

text    0
spam    0
dtype: int64

In [151]:
## lowercase the text
df["text"] = df["text"].str.lower()
df.head()

                                                text  spam
0  subject: naturally irresistible your corporate...     1
1  subject: the stock trading gunslinger  fanny i...     1
2  subject: unbelievable new homes made easy  im ...     1
3  subject: 4 color printing special  request add...     1
4  subject: do not have money , get software cds ...     1

In [152]:
nltk.download("stopwords")
from nltk.corpus import stopwords
stop = set(stopwords.words("english"))
def clean_text(text):
    tokens = re.sub(r"\d+", " ", text) ## it will remove all the digits
    tokens = re.sub(r"_"," ", tokens) ## it will remove all the underscores
    tokens = re.sub(r"\W", " ", tokens) ## it will remove all the special characters
    tokens = [i for i in tokens.split() if i not in stop]
    tokens = " ".join(tokens)
    return tokens
df["text"] = df["text"].apply(clean_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\NachiketDixit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [160]:
df["text"].iloc[2155]

'subject efa meetings hey vince thanks reply see becomes session keep informed paper tim crack revised version paper gave since found using certainty equivalence model robust example one asset pricing model incorporates mean variance skewness harvey siddique jf june binomial model incorporates mean variance skewness johnson paulukiewicz mehta rqfa model allows price options real world measure benefit one take model parameters historical data non risk neutralized pricing perspective tremendous benefit mean variance world variance stays risk neutral risky measure however mean variance skewness world benefit believe although still hunting appropriate cite skewness risk neutral risky measure given measure skewness risky world model becomes much significant would certainly appreciate comments version paper would also pass new version paper would like see thanks tom'

In [161]:
## Lemmatization
from nltk.stem import WordNetLemmatizer
nltk.download("wordnet")
lemma = WordNetLemmatizer()
for i in range(len(df)):
    df["text"].iloc[i] = lemma.lemmatize(df["text"].iloc[i])

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\NachiketDixit\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
C:\Users\NachiketDixit\AppData\Local\Temp\ipykernel_22664\2957659433.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df["text"].iloc[i] = lemma.lemmatize(df["text"].iloc[i])

In [164]:
df["text"].iloc[0]

'subject naturally irresistible corporate identity lt really hard recollect company market full suqgestions information isoverwhelminq good catchy logo stylish statlonery outstanding website make task much easier promise havinq ordered iogo company automaticaily become world ieader isguite ciear without good products effective business organization practicable aim hotat nowadays market promise marketing efforts become much effective list clear benefits creativeness hand made original logos specially done reflect distinctive company image convenience logo stationery provided formats easy use content management system letsyou change website content even structure promptness see logo drafts within three business days affordability marketing break make gaps budget satisfaction guaranteed provide unlimited amount changes extra fees surethat love result collaboration look portfolio interested'

## Text to Vectors: - 
1. Bag of Words

In [167]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x = cv.fit_transform(df["text"]).toarray()
y = df["spam"]

In [169]:
x.shape

(5695, 33545)

In [170]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [173]:
## classification ---> Baseline
from sklearn.metrics import accuracy_score


model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(accuracy_score(y_train, y_pred_train))
print(accuracy_score(y_test, y_pred))

1.0
0.9885864793678666

In [174]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print(accuracy_score(y_test, y_pred))

0.9920983318700615

In [190]:
cv2 = CountVectorizer(max_features=1000, ngram_range=(1,3))
x2 = cv2.fit_transform(df["text"]).toarray()

In [192]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x2, y,test_size=0.2, random_state=42)

In [194]:
model_ngram = MultinomialNB()
model_ngram.fit(x_train, y_train)
y_pred_ngram_train = model_ngram.predict(x_train)
print(accuracy_score(y_train, y_pred_ngram_train))
y_pred_ngram = model_ngram.predict(x_test)
print(accuracy_score(y_test, y_pred_ngram))

0.9620280948200176
0.9666374012291484

In [195]:
## tfidf vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=1000, ngram_range=(1,3))
x3 = tfidf.fit_transform(df["text"]).toarray()

In [196]:
model3 = MultinomialNB()
model3.fit(x_train, y_train)
y_pred3_train = model3.predict(x_train)
print(accuracy_score(y_train, y_pred3_train))
y_pred3 = model3.predict(x_test)
print(accuracy_score(y_test, y_pred3))

0.9620280948200176
0.9666374012291484

In [197]:
y_test

1436    0
748     1
4126    0
1448    0
3905    0
       ..
2765    0
219     1
1831    0
1115    1
582     1
Name: spam, Length: 1139, dtype: int64

In [199]:
y_pred3

array([0, 1, 0, ..., 0, 1, 1], shape=(1139,))